adapters:
  rubicon:
    enabled: true
    XAPI.Username: rubiuser
    XAPI.Password: rubipw23
  appnexus:
    enabled: true
  pubmatic:
    enabled: true
  sovrn:
    enabled: true
  openx:
    enabled: true
  lockerdome:
    enabled: true
  conversant:
    enabled: true
  apdummy:
    enabled: true
    endpoint: http://127.0.0.1:8081/test
metrics:
  prefix: prebid
cache:
  scheme: http
  host: localhost:2424
  path: /cache
  query: uuid=
settings:
  filesystem:
    enabled: true
    settings-filename: sample/sample-app-settings.yaml
    stored-requests-dir: sample/stored_requests
    stored-imps-dir: sample/stored_requests
    stored-responses-dir: sample/stored_requests
gdpr:
  default-value: 0
  vendorlist:
    v1:
      cache-dir: /var/tmp/vendor1
    v2:
      cache-dir: /var/tmp/vendor2
geolocation:
  enabled: true
  type: maxmind
  maxmind:
    remote-file-syncer:
      download-url: # URL for GeoLite2-City.tar.gz
      save-filepath: sample/prebid/GeoLite2-City.tar.gz
      tmp-filepath: sample/prebid/tmp/GeoLite2-City.tar.gz
      retry-count: 3
      retry-interval-ms: 3000
      timeout-ms: 600000
      update-interval-ms: 0
      http-client:
        connect-timeout-ms: 2500
        max-redirects: 3
status-response: "ok"
logger-level-modifier:
  enabled: true
adpushup:
  imd-feedback-host: "http://localhost:8082"
  imd-feedback-endpoint: "/imd_feedback"
  imd-feedback-creative-endpoint: "/creativecall"
  customConfig:
    couchbase-ips: 127.0.0.1:8091
    couchbase-username: Administrator
    couchbase-password: password
    elasticsearch-host: 127.0.0.1