status-response: "ok"
adapters:
  rubicon:
    enabled: true
    XAPI.Username: rubiuser
    XAPI.Password: rubipw23
  appnexus:
    enabled: true
  pubmatic:
    enabled: true
  sovrn:
    enabled: true
  openx:
    enabled: true
  lockerdome:
    enabled: true
  conversant:
    enabled: true
metrics:
  prefix: prebid
cache:
  scheme: http
  host: localhost:2424
  path: /cache
  query: uuid=
settings:
  filesystem:
    enabled: true
    settings-filename: sample/sample-app-settings.yaml
    stored-requests-dir: sample/stored_requests
    stored-imps-dir: sample/stored_requests
    stored-responses-dir: sample/stored_requests
gdpr:
  default-value: 0
  vendorlist:
    v1:
      cache-dir: /var/tmp/vendor1
    v2:
      cache-dir: /var/tmp/vendor2
